apiVersion: logging.d3os.io/v1alpha2
kind: Input
metadata:
  name: docker
  namespace: d3os-logging-system
  labels:
    logging.d3os.io/enabled: "true"
    logging.d3os.io/component: logging
spec:
  systemd:
    tag: service.docker
    path: /var/log/journal
    db: /fluent-bit/tail/docker.db
    dbSync: Normal
    systemdFilter:
      - _SYSTEMD_UNIT=docker.service
