apiVersion: logging.d3os.io/v1alpha2
kind: Input
metadata:
  name: tail
  namespace: d3os-logging-system
  labels:
    logging.d3os.io/enabled: "true"
    logging.d3os.io/component: "logging"
spec:
  tail:
    tag: kube.*
    path: /var/log/containers/*.log
    parser: docker
    refreshIntervalSeconds: 10
    memBufLimit: 5MB
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal
    excludePath: /var/log/containers/*_d3os-logging-system_events-exporter*.log,/var/log/containers/kube-auditing-webhook*_d3os-logging-system_kube-auditing-webhook*.log

