apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  labels:
    thanos-ruler: d3os
  name: d3os
  namespace: d3os-monitoring-system
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: thanos-ruler
              operator: In
              values:
              - d3os
          namespaces:
          - d3os-monitoring-system
          topologyKey: kubernetes.io/hostname
        weight: 100
  alertmanagersUrl:
  - dnssrv+http://alertmanager-operated.d3os-monitoring-system.svc:9093
  image: thanosio/thanos:v0.18.0
  queryEndpoints:
  - prometheus-operated.d3os-monitoring-system.svc:9090
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      role: thanos-alerting-rules
      thanosruler: thanos-ruler