apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentbit-operator-migrator
  namespace: d3os-logging-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - logging.d3os.io
    resources:
      - outputs
    verbs:
      - create

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-operator-migrator
  namespace: d3os-logging-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentbit-operator-migrator
  namespace: d3os-logging-system
roleRef:
  kind: Role
  name: fluentbit-operator-migrator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentbit-operator-migrator
    namespace: d3os-logging-system