---
- name: d3os | Checking account init
  shell: >
    {{ bin_dir }}/kubectl get users admin
  register: d3os_user_check
  failed_when: "d3os_user_check.stderr and 'NotFound' not in d3os_user_check.stderr"

- name: d3os | Initing account
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ d3os_dir }}/ks-init/initial-account.yaml
  when:
    - d3os_user_check.stderr is defined
    - d3os_user_check.stderr.find("NotFound") != -1

