apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s-config
  namespace: d3os-monitoring-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
