apiVersion: v1
kind: Service
metadata:
  name: d3os-router-gateway
  labels:
    app: d3os
    component: ks-router
    tier: backend
spec:
  selector:
    app: d3os
    component: ks-router
    tier: backend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

