- name: ks-events | Getting logging installation files
  copy:
    src: "fluentbit-operator"
    dest: "{{ d3os_dir }}/"


- name: ks-events | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ d3os_dir }}/fluentbit-operator/{{ item.file }}"
  with_items:
    - { name: custom-output-elasticsearch-events, file: custom-output-elasticsearch-events.yaml }

- name: ks-events | Apply fluentbit operator custom resources
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ d3os_dir }}/fluentbit-operator