---

- import_tasks: precheck.yaml

- name: d3os | Checking d3os component
  shell: >
    {{ bin_dir }}/kubectl get deploy -n d3os-system
  register: d3os_component_deployment

- name: d3os | Getting d3os component version
  shell: >
    {{ bin_dir }}/kubectl get deploy -n  d3os-system ks-console -o jsonpath='{.metadata.labels.version}'
  register: console_version
  when:
    - d3os_component_deployment.stdout.find("ks-console") != -1

- import_tasks: helm-migrate.yaml
  when:
    - d3os_component_deployment.stdout.find("ks-console") != -1
    - console_version.stdout is version('v3.0.0', '<')
