---
- block:
  - name: d3os | Getting sonarqube host
    shell: >
      {{ bin_dir }}/kubectl get cm -n d3os-system d3os-config -o jsonpath='{.data.d3os\.yaml}' | grep "sonarQube:" -A 2 | grep "host" | awk '{print $2}'
    register: sonarqube_host

  - name: d3os | Getting sonarqube token
    shell: >
      {{ bin_dir }}/kubectl get cm -n d3os-system d3os-config -o jsonpath='{.data.d3os\.yaml}' | grep "sonarQube:" -A 2 | grep "token" | awk '{print $2}'
    register: sonarqube_token
  when:
    - devops.sonarqube is not defined

- set_fact:
    sonarQubeHost: "{{ sonarqube_host.stdout }}"
    sonarQubeToken: "{{ sonarqube_token.stdout }}"
  when:
    - sonarqube_host is defined and sonarqube_host.stdout is defined and sonarqube_host.stdout != ""
    - sonarqube_token is defined and sonarqube_token.stdout is defined and sonarqube_token.stdout != ""

- set_fact:
    sonarQubeHost: "{{ devops.sonarqube.externalSonarUrl }}"
    sonarQubeToken: "{{ devops.sonarqube.externalSonarToken }}"
  when:
    - devops.sonarqube is defined
    - devops.sonarqube.externalSonarUrl is defined
    - devops.sonarqube.externalSonarToken is defined

- block:
  - name: d3os | Getting es host
    shell: >
      {{ bin_dir }}/kubectl get cm -n d3os-system d3os-config -o jsonpath='{.data.d3os\.yaml}' | grep "logging:" -A 2 | grep "host" | awk '{print $2}'
    register: es_host

  - name: d3os | Getting es index prefix
    shell: >
      {{ bin_dir }}/kubectl get cm -n d3os-system d3os-config -o jsonpath='{.data.d3os\.yaml}' | grep "logging:" -A 2 | grep "indexPrefix" | awk '{print $2}'
    register: es_indexPrefix

- set_fact:
    esHost: "{{ es_host.stdout }}"
    esIndexPrefix: "{{ es_indexPrefix.stdout }}"
  when:
    - es_host is defined and es_host.stdout is defined and es_host.stdout != ""
    - es_indexPrefix is defined and es_indexPrefix.stdout is defined and es_indexPrefix.stdout != ""

- name: d3os | Getting token
  shell: >
    {{ bin_dir }}/kubectl get secret d3os-secret -o jsonpath='{.data.token}' | base64 -d
  register: ks_token_str

- name: d3os | Getting ks-secret
  shell: >
    {{ bin_dir }}/kubectl get secret d3os-secret -o jsonpath='{.data.secret}' | base64 -d
  register: ks_secret_str

- name: d3os | Checking Kubernetes version
  shell: >
    {{ bin_dir }}/kubectl version -o json | jq '.serverVersion.gitVersion' | sed s/\"//g
  register: kubernetes_version

- debug:
    msg: Current Kubernetes version is {{kubernetes_version.stdout}}

# Get the matched kubectl image
- name: d3os | Setting kubectl image version
  set_fact:
    ks_kubectl_tag: "{{item.value}}"
    kubectl_break: true
  loop: "{{ query('dict', ks_kubectl_versions) }}"
  when:
    - kubectl_break is undefined and kubernetes_version is defined and kubernetes_version.stdout is version(item.key, '>=')

- debug:
    msg: Current kubectl image version is {{ks_kubectl_tag}}

- name: d3os | Getting Kubernetes master num
  shell: >
    {{ bin_dir }}/kubectl get node | awk '{if(NR>1){print $3}}' | grep master | wc -l
  register: masters
  failed_when: false


- name: d3os | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}
  when:
    - enableHA is not defined

- name: OpenPitrix | Check OpenPitrix v3.0.0
  shell: >
    {{ bin_dir }}/kubectl get deploy openpitrix-hyperpitrix-deployment -n openpitrix-system 2>1 -oNAME | wc -l
  register: openpitrix_deploy_count

- set_fact:
    OPMigrate: true
  when:
    - openpitrix_deploy_count.stdout == "1"

- name: d3os | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ d3os_dir }}/{{ item.file }}"
  with_items:
    - { name: d3os-config, file: d3os-config.yaml, type: cm }


- name: d3os | Initing d3os
  shell: "{{ bin_dir }}/kubectl apply -f {{ d3os_dir }}/{{ item }}"
  loop:
    - "d3os-config.yaml"
  register: init_result
  failed_when: "init_result.stderr and 'AlreadyExists' not in init_result.stderr"

- import_tasks: ks-restart.yaml
