---

- name: d3os | Loading old openldap data
  shell: >
    {{ bin_dir }}/kubectl -n d3os-system exec -it
    $(kubectl get pod -n d3os-system -l app=openldap,tier=database,version=openldap-2.4 -ojsonpath='{.items[0].metadata.name}')
    /usr/sbin/slapcat > {{ d3os_dir }}/ldapdbak.ldif


- name: d3os | Checking openldap-ha status
  shell: >
    {{ bin_dir }}/kubectl get pod -n d3os-system
    -l app.kubernetes.io/name=openldap-ha | awk '{if(NR>1){print}}' | grep -v '1/1' | wc -l
  register: ldap_status
  until: ldap_status.stdout == "0"
  retries: 30
  delay: 30


- name: d3os | Getting openldap-ha pod list
  shell: >
    {{ bin_dir }}/kubectl get pod -n d3os-system
    -l app.kubernetes.io/name=openldap-ha | awk '{if(NR>1){print $1}}'
  register: podList


- name: d3os | Getting old openldap data
  shell: >
    {{ bin_dir }}/kubectl -n d3os-system cp
    {{ d3os_dir }}/ldapdbak.ldif
    {{ item }}:/tmp/ldapdbak.ldif
  loop: "{{ podList.stdout_lines }}"


- name: d3os | Migrating openldap data
  shell: >
    kubectl -n d3os-system exec -it {{ item }} -- sh -c
    'rm -rf /var/lib/ldap/* && /usr/sbin/slapadd -l /tmp/ldapdbak.ldif && chown -R openldap:openldap /var/lib/ldap/*'
  loop: "{{ podList.stdout_lines }}"


- name: d3os | Disabling old openldap
  shell: >
    {{ bin_dir }}/kubectl -n d3os-system scale deployment openldap --replicas=0


#- name: d3os | Restarting openldap
#  shell: >
#    {{ bin_dir }}/kubectl -n d3os-system rollout restart sts/openldap

- name: d3os | Restarting openldap
  shell: >
    {{ bin_dir }}/kubectl delete pod -n d3os-system -l app.kubernetes.io/instance=ks-openldap
