- name: d3os | Checking ha-redis
  shell: >
    {{ bin_dir }}/helm list -n d3os-system | grep "ks-redis"
  register: redis_check
  failed_when: false


- name: d3os | Deploying ha redis
  block:

    - name: d3os | Getting redis installation files
      copy:
        src: "{{ item }}"
        dest: "{{ d3os_dir }}/"
      loop:
        - "redis-ha"


    - name: d3os | Creating manifests
      template:
        src: "{{ item.file }}.j2"
        dest: "{{ d3os_dir }}/{{ item.file }}"
      with_items:
        - { name: custom-values-redis, file: custom-values-redis.yaml }


    - name: d3os | Checking old redis status
      shell: >
        {{ bin_dir }}/kubectl get pod -n d3os-system  -l app=redis,tier=database,version=redis-4.0 | wc -l
      register: old_redis_exist


    - name: d3os | Deleting and backup old redis svc
      shell: >
        {{ bin_dir }}/kubectl get svc -n d3os-system redis -o yaml > {{ d3os_dir }}/redis-svc-backup.yaml
        &&
        {{ bin_dir }}/kubectl delete svc -n d3os-system redis
      when:
        - old_redis_exist.stdout != "0"


    - name: d3os | Deploying redis
      shell: >
        {{ bin_dir }}/helm upgrade --install ks-redis
        {{ d3os_dir }}/redis-ha
        -f {{ d3os_dir }}/custom-values-redis.yaml
        --set fullnameOverride=redis-ha
        --namespace d3os-system


#    - name: d3os | Getting redis PodIp
#      shell: >
#        {{ bin_dir }}/kubectl get pod
#        -n d3os-system
#        -l  app=redis,tier=database,version=redis-4.0
#        -ojsonpath='{.items[0].status.podIP}'
#      register: redis_podIp
#      when:
#        - old_redis_exist.stdout != "0"
#
#
#    - import_tasks: redis-migration.yaml
#      when:
#        - old_redis_exist.stdout != "0"

  when:
    - enableHA is defined and enableHA
    - (redis_check.stdout.find("deployed") == -1) or (redis_check.stdout.find("5.0.5") == -1)


- name: d3os | Deploying redis
  shell: >
    {{ bin_dir }}/kubectl -n d3os-system apply -f {{ d3os_dir }}/common/{{ item }}
  loop:
    - "redis.yaml"
  register: redis_result
  failed_when:
    - "redis_result.stderr and 'bound claims' not in redis_result.stderr"
    - "redis_result.stderr and 'is forbidden' not in redis_result.stderr"
  when:
    - (enableHA is defined and not enableHA) or (enableHA is not defined)


- name: d3os | Importing redis status
  shell: >
    {{ bin_dir }}/kubectl patch cc ks-installer
    --type merge
    -p '{"status": {"redis": {"status": "enabled", "enabledTime": "{{ lookup('pipe','date  +%Y-%m-%dT%H:%M:%S%Z') }}"}}}'
    -n d3os-system
  register: cc_result
  failed_when: "cc_result.stderr and 'Warning' not in cc_result.stderr"
  until: cc_result is succeeded
  retries: 5
  delay: 3