
- name: d3os | Creating redis migration script
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ d3os_dir }}/{{ item.file }}"
  with_items:
    - { path: /etc/d3os, file: redisMigrate.py }


- name: d3os | Checking redis-ha status
  shell: >
    {{ bin_dir }}/kubectl get pod -n d3os-system | grep 'redis-ha' | grep -v 'Running' | wc -l
  register: redis_result
  until: redis_result.stdout == "0"
  retries: 30
  delay: 30


- name: ks-logging | Migrating redis data
  shell: >
    chmod +x {{ d3os_dir }}/redisMigrate.py &&
    {{ d3os_dir }}/redisMigrate.py


- name: d3os | Disabling old redis
  shell: >
    {{ bin_dir }}/kubectl -n d3os-system scale deployment redis --replicas=0