operator:
  enabled: true
  image:
    repository: d3osdev/kube-events-operator
    tag: v0.1.0
    pullPolicy: IfNotPresent
  configReloader:
    image: jimmidyson/configmap-reload:v0.3.0
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 200Mi
#    requests:
#      cpu: 20m
#      memory: 20Mi
  serviceAccount:
    create: true
    name: ""
  # If true, just clean up cr but not crd
  cleanupAllCustomResources: false
  kubectlImage: docker.io/bitnami/kubectl:1.14.1

exporter:
  enabled: true
  image:
    repository: d3osdev/kube-events-exporter
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources: {}
#    limits:
#      cpu: 200m
#      memory: 500Mi
#    requests:
#      cpu: 20m
#      memory: 50Mi
  sinks:
    stdout:
      enabled: true
    additionalWebhooks: []
    # - url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:

ruler:
  enabled: true
  replicas: 2
  image:
    repository: d3osdev/kube-events-ruler
    tag: v0.1.0
    pullPolicy: IfNotPresent
  resources: {}
#    limits:
#      cpu: 500m
#      memory: 500Mi
#    requests:
#      cpu: 50m
#      memory: 50Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  sinks:
    alertmanager:
      namespace: d3os-monitoring-system
      name: alertmanager-main
    webhooks: []
    # - type:
    #   url:
    #   service:
    #     namespace:
    #     name:
    #     port:
    #     path:

rule:
  createDefaults: true
  overrideDefaults: false