apiVersion: logging.d3os.io/v1alpha2
kind: Filter
metadata:
  name: filter-events
  namespace: d3os-logging-system
  labels:
    logging.d3os.io/enabled: "true"
    logging.d3os.io/component: "events"
spec:
  match: kube_events
  filters:
    - parser:
        keyName: log
        parser: json