apiVersion: logging.d3os.io/v1alpha2
kind: Input
metadata:
  labels:
    logging.d3os.io/enabled: 'true'
    logging.d3os.io/component: "auditing"
  name: tail-auditing
  namespace: d3os-logging-system
spec:
  tail:
    db: /fluent-bit/tail/pos-auditing.db
    dbSync: Normal
    memBufLimit: 5MB
    parser: docker
    path: /var/log/containers/kube-auditing-webhook*_d3os-logging-system_kube-auditing-webhook*.log
    refreshIntervalSeconds: 10
    skipLongLines: true
    tag: kube_auditing

