---

- hosts: localhost
  gather_facts: false
  roles:
    - d3os-defaults
    - role: ks-logging
      when:
        - "status.logging is not defined or status.logging.status is not defined or status.logging.status != 'enabled'"