apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: network.d3os.io
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVTVVONE92YkhPaFRjN0VhL05iUXprUlpleXZVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl6TURJeU9EQTVNalV3TUZvWERUSTRNREl5TnpBNU1qVXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcnJTYnhlU0NHNHRVb0NuWVRuMysKSXZ3eWlKNWdsOGNQbHZhTVp1YXdiU2lkVTJWMGhGTDIxTVNvRXlhMDltR1dHVWI1Qk5ZNmZnZ0dBcXNMK25rYwpYNWp1QktCRDZHeU50UENUVXZuZGkxOCs3eUVPL3kwdFFnbVQ1ZksrWm5wTXdlTEYxeVM5UmVXbDByZldUcWl2ClBpSDZUTGJacExPNmcwQlVYV3dRelg1UFdUODFJc2V1MFJLU3lTWG5KbFU5THdwVUluU093d1RWLzhPUE9NMXoKZGRCQUV4QXUvVTFzVjNmRTV6akw5bnFadTAwV3RiY2JjL2RMS3cxK04vaVJSUU9yZnF0ZWdua0lzRjhlV1VPTwpLa3lkR0ZHNVA3Q0VXSm1OTmNYMytjUFl3WkE3dDR5Wk4zL0hhK0ZVWkdhV2NtMHE0Y3VVcFB0cDdPSWJEc0I1CnJRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVdURtcGkrc2VaU3h2VTFtU3VTOGR4QmNRRUpJd0h3WURWUjBqQkJnd0ZvQVV1RG1waStzZQpaU3h2VTFtU3VTOGR4QmNRRUpJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBNzdCZG9iZ3pJZHJiaDJkNXFVCnRiUS9oRzgrNUdzUWNwTDlwNWkwTUlPcFE3dEZRT3ZzWko5YmtubTRhY05tcFA4YlhhU25scVRrQlRIeUoxWmoKZGk4N2hIWWV0eTN3YnRMYkZKTDFkUmtlK0tVWWNYRmtzd1hhVzkyUnMzbGcxd1B6cXFqV0xMRUlQWU0wQVdLcwplb3BoUDFrQVlIcTMxVlpvbkFHTnZWYWlOaVBQZFMwcjJxa0RuaUtoa1RZUmtEMkZxVXl2QVFXMURxbFRCNVk0Ck1VMFF4Zm5mcmNKS2ZlVnM4TG9RcjhJZ2tNTi9lNGdnSEVqcWFsSGd2VEJ4b09HYkRMQ200UXVQcVVDYnNrK0kKcDNuY2tTNWY4dm1NYmkvbFJhVFQ1V3JoTGxtTzZyZTdIbnFRdGd4RUZxYmdKVFBlYVdNRFdVUGZVTEtYbjlXMgpMTjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
      service:
        name: ks-controller-manager
        namespace: d3os-system
        path: /validate-network-d3os-io-v1alpha1
        port: 443
    failurePolicy: Fail
    matchPolicy: Exact
    name: validating-network.d3os.io
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    objectSelector: {}
    rules:
      - apiGroups:
          - network.d3os.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - ippools
        scope: '*'
    sideEffects: None
    timeoutSeconds: 30
